DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS comment;

CREATE TABLE image (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  );


CREATE TABLE comment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL,
  image_id INTEGER NOT NULL,
  FOREIGN KEY (image_id) REFERENCES image (id)
  );